config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :users

  root 'home#index'

  # sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'

  # routes for tags
  get 'tagged', to: 'songs#tagged', as: 'tagged'
  get 'tags/:tag', to: 'songs#index', as: :tag

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :songs

	validates :user_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true


  has_secure_password
  	def self.confirm(params)
    	@user = User.find_by({email: params[:email]})
    	@user.try(:authenticate, params[:password])
  end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	# GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find(params[:id])
    if current_user == nil
      redirect_to sign_in_path
    else
      render :show
    end
  end

  # GET /users/new
  def new
    @user = User.new
    render :new
  end

  # GET /users/1/edit
  def edit
  	@user = User.find(params[:id])
    render :user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email, :password_digest)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	# GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
     respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @shippings }
     end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  	@user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
		# User.save(:user_id)
    #respond_to do |format|
			@user.save
    	login(@user)
        flash[:success] = "Welcome to Lyrical!"
        redirect_to '/users/' + @user.id.to_s
      #else
        #redirect_to new_user_path, flash: {error: @user.errors.full_messages.to_sentence}
      #end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email, :password)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<div class="row formCard">
	<% if new_user %>
	<h2 class="profileTitle titles">Sign Up</h2>
	<% end %>
  <br>
	<% options = new_user ? {url: users_path, method: "POST"} : {url: user_path, method: "PATCH"} %>
	<%= form_for @user, options do |f| %>
  <div class="row form">
  	<div class="large-6 columns">
		  <%= f.text_field :user_name, placeholder: "Username", class: "form-control" %>
		  <%= f.text_field :email, placeholder: "Email", class: "form-control"  %>
		  <%= f.password_field :password, placeholder: "Password", class: "form-control"  %>
	  	<button type="submit" class="button interests">Submit</button>
		</div>
	</div>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', new_user: false %>

<!-- <%= button_to 'User Profile', @user, class: 'button' %>
<%= button_to 'Back', users_path, class: 'button', method: :get %> -->

app/views/users/index.html.erb
<div class = "container">
	<p>User Index</p>
</div>
<div class="container">
	<ul>
		<% @users.each do |user| %>
		<li>
  			<a href="/users/<%= user.id %>" ><%= user.user_name %></a>
  		</li>
     	<% end %>
     </ul>
 </div>

     

app/views/users/new.html.erb
<%= render 'form', new_user: true %>

app/views/users/show.html.erb
<p>
  <h3>Welcome, <%= @user.user_name %>!</h3>

</p>
<div class"container">
	<strong>Email:</strong>
	<%= @user.email %>
</div>

<br>
<%= link_to 'Edit Your User Info', edit_user_path(@user) %> |
<%= link_to 'Back', user_path %>
<br>
<br>
<div class"container">
<h5>Your Songs</h5>
</div>
<br>
<div class="row">
<% @user.songs.each do |song| %>
      <tr>
        <td><strong><%= song.title %></strong></td>
        <td><%= song.lyrics %></td>
        <td><%= song.origin %></td>
        <td><%= song.image %></td>
        <br>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <br><br>
    <% end %>
</div>
<br>
<div class="row">
  <%= button_to 'New Song', new_song_path, :method => :get%>
</div>