config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :users

  root 'home#index'

  # sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'

  # routes for tags
  get 'tagged', to: 'songs#tagged', as: 'tagged'
  get 'tags/:tag', to: 'songs#index', as: :tag

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<p> Testing for footer content </p>

app/views/application/_header.html.erb
<!-- Nav Bar -->
<div class="top-bar folk_bar">
  <div class="top-bar-left">
    <!-- <a href="/"><img src="/assets/images/lyricalblue.png"/></a>  -->
     <a href="/" class="menu-text">Lyrical</a>

  </div>
  

<div class="top-bar-right">
    <ul class="menu">
      <li class="menu"><%= link_to "All Songs List", songs_path, method: :get, class: "button folk_button" %></li>
      <% if current_user %>
        <li class="menu"><%= link_to 'My Songs', user_path(current_user), method: :get, class: "button folk_button" %></li>
        
        
        <li class="menu"><%= link_to "Sign Out", sessions_path, method: :delete, class: "button folk_button" %></li>
      <% else %>
        
        <li class="menu"><%= link_to "Login", sign_in_path, method: :get, class: "button folk_button" %></li>
        <li class="menu"><%= link_to "Sign up", new_user_path, method: :get, class: "button folk_button" %></li>

      <% end %>

    </ul>
  </div>
</div>